// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtqqmuwjfgeydwcbuaqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cXFtdXdqZmdleWR3Y2J1YXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDgzNDMsImV4cCI6MjA3MTMyNDM0M30.kCnO8qfJ26BHVa8cOCspiPXA20Bdddi-LuRG4J7Q1pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});